# proto-file: intrinsic/skills/proto/skill_manifest.proto
# proto-message: SkillManifest

# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id {
  package: "ai.intrinsic"
  name: "capture_images"
}
display_name: "Capture images"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description:
    "Captures sensor images from the specified camera internally using the "
    "camera service."
}
extended_documentation {
  usage_example:
    "import Tabs from '@theme/Tabs';\n"
    "import TabItem from '@theme/TabItem';\n"
    "\n"
    "To retrieve and consume the capture result contained in the returned "
    "<a href=\"#capture_data\">`capture_data`</a>, use the following code:\n"
    "<Tabs>\n"
    "<TabItem value=\"python\" label=\"Python\">\n"
    "```python\n"
    "from intrinsic.perception.proto.v1 import capture_result_pb2\n"
    "from intrinsic.platform.pubsub.python import pubsub\n"
    "\n"
    "pub_sub = pubsub.PubSub()\n"
    "kvstore = pub_sub.KeyValueStore(capture_data.capture_result_location.store)\n"
    "capture_result = capture_result_pb2.CaptureResult()\n"
    "kvstore.Get(capture_data.capture_result_location.key).Unpack(capture_result)\n"
    "```\n"
    "</TabItem>\n"
    "<TabItem value=\"cpp\" label=\"C++\">\n"
    "```cpp\n"
    "#include \"intrinsic/perception/proto/v1/capture_result.proto.h\"\n"
    "#include \"intrinsic/platform/pubsub/pubsub.h\"\n"
    "\n"
    "PubSub pubsub;\n"
    "INTR_ASSIGN_OR_RETURN(\n"
    "    KeyValueStore kvstore,\n"
    "    pubsub.KeyValueStore(capture_data.capture_result_location().store()));\n"
    "INTR_ASSIGN_OR_RETURN(\n"
    "    auto capture_result,\n"
    "    kvstore.Get<intrinsic_proto::perception::v1::CaptureResult>(\n"
    "        capture_data.capture_result_location().key(), NamespaceConfig()));\n"
    "```\n"
    "</TabItem>\n"
    "</Tabs>\n"
}
options {
  cancellation_ready_timeout {
    seconds: 30
  }
  cc_config {
    create_skill: "::intrinsic::skills::CaptureImages::CreateSkill"
  }
}
parameter {
  message_full_name: "intrinsic_proto.skills.CaptureImagesParams"
  default_value {
    [type.googleapis.com/intrinsic_proto.skills.CaptureImagesParams] {
      capture_result_location {
        store: "capture_results"
      }
      timeout { seconds: 5 }
    }
  }
}
return_type {
  message_full_name: "intrinsic_proto.skills.CaptureImagesResult"
}
